#whole documentation will be in english
name: ModularMSMF-Basics
version: ${version}
description: Basic commands to enhance user experience and ease management
website: ${url}
authors: [Lightkeks, davidmc971]

depend:
  - "ModularMSMF-Core"

api-version: 1.19

main: io.github.davidmc971.modularmsmf.basics.ModularMSMFBasics

# TODO: load at runtime with our secret haxx
commands:
  get:
    description: Get specific values from players.
    usage: /<command> <args> <player>
  set:
    description: Set specific values for players.
    usage: /<command> <args> <int> <player>
  channel:
    description: Set, create, change or remove channels.
    usage: /<command> <label> <args>
  #  toggle:
  #    description: toggle cmds
  #    usage: /<command> <args>
  #    aliases: [tog]
  teleport:
    description: Teleport players.
    usage: /<command> <target>
    aliases: [tp, tele]
  heal:
    description: Heals player.
    usage: /<command> <target>
  healall:
    description: Heal all players.
    usage: /<command>
  feed:
    description: Feed player.
    usage: /<command> <player>
  ban:
    description: Banning players optional with reason.
    usage: /<command> <player> <args>
  unban:
    description: Unban a player.
    usage: /<command> <player>
  banip:
    description: Bans a player by IP with optional reason.
    usage: /<command> <player> <args>
  unbanip:
    description: Unbans a player's IP.
    usage: /<command> <args>
  kick:
    description: Kick player with optional reason
    usage: /<command> <player> <args>
  kill:
    description: Kill player.
    usage: /<command> <args>
  killall:
    description: Kill everyone.
    usage: /<command>
  killme:
    description: Do suicide.
    usage: /<command>
  mute:
    description: Mute a player.
    usage: /<command> <player>
  motd:
    description: Message-Of-The-Day.
    usage: /<command> <args>
  slaughter:
    description: Destroy entities.
    usage: /<command> <args>
  home:
    description: Teleports you home. Optionally specify a home name. Also sets homes.
    usage: /<command> <args>
  setspawn:
    description: Set the spawn.
    usage: /<command>
  spawn:
    description: Spawns the player.
    usage: /<command>
  back:
    description: Gets back the player to the last position.
    usage: /<command>
  fly:
    description: Let the player fly.
    usage: /<command> <args>
  clearinventory:
    description: Clear's inventory of an player.
    usage: /<command> <name>
    aliases: [ci, clearinv]
