name: ModularMSMF-Basics
version: ${version}
description: Basic commands to enhance user experience and ease management
website: ${url}
authors: [Lightkeks, davidmc971]

depend:
  - "ModularMSMF-Core"

api: none

main: io.github.davidmc971.modularmsmf.basics.ModularMSMFBasics

# TODO: load at runtime with our secret haxx
commands:
  get:
    description: get values
    usage: /<command> <args> <player>
  set:
    description: set values
    usage: /<command> <args> <int> <player>
  channel:
    description: channels
    usage: /<command> <label> <args>
  #  toggle:
  #    description: toggle cmds
  #    usage: /<command> <args>
  #    aliases: [tog]
  teleport:
    description: teleportation zu einem Spieler.
    usage: /<command> <target>
    aliases: [tp, tele]
  heal:
    description: Heilt Spieler.
    usage: /<command> <target>
  healall:
    description: heal all players
    usage: /<command>
  feed:
    description: Saettigt den Spieler.
    usage: /<command> <player>
  ban:
    description: Bannt einen Spieler.
    usage: /<command> <player>
  unban:
    description: Entbannt einen Spieler.
    usage: /<command> <player> <args>
  ban-ip:
    description: Bans a player by IP.
    usage: /<command> <args>
  kick:
    description: Kickt einen Spieler.
    usage: /<command> <player>
  kill:
    description: Killt einen Spieler.
    usage: /<command> <args>
  mute:
    description: Mutet einen Spieler.
    usage: /<command> <player>
  motd:
    description: Message Of The Day.
    usage: /<command> <args>
  slaughter:
    description: Destroy entities.
    usage: /<command> <args>
  home:
    description: Teleports you home. Optionally specify a home name. Also sets homes.
    usage: /<command> <args>
  setspawn:
    description: Set the spawn
    usage: /<command>
  spawn:
    description: Spawns the player
    usage: /<command>
  back:
    description: Gets back the player to the last position
    usage: /<command>
  fly:
    description: Let the player fly
    usage: /<command> <args>
