name: ModularMSMF-NovaPerms
version: ${version}
description: NovaPerms - group and user permission management right at your fingertips
website: ${url}
authors: [Lightkeks, davidmc971]

depend:
  - "ModularMSMF-Core"

api: none

main: io.github.davidmc971.modularmsmf.novaperms.ModularMSMFNovaPerms

commands:
  asdasdasdasdasdasd:
    description: asdasdasdasdasd
    usage: /<command> <args>