name: ModularMSMF-CommandBlocker
version: ${version}
description: Easily block any command from any plugin
website: ${url}
authors: [Lightkeks, davidmc971]

depend:
  - "ModularMSMF-Core"

api: none

main: io.github.davidmc971.modularmsmf.commandblocker.ModularMSMFCommandBlocker

commands:
  commandblocker:
    description: Configure CommandBlocker
    usage: /<command> <args>
    aliases: [cmdblckr, cb]
