name: ModularMSMF-Core
version: ${version}
description: The Core of the Modular Minecraft Server Management Framework
website: ${url}
authors: [Lightkeks, davidmc971]

api: none

main: io.github.davidmc971.modularmsmf.core.ModularMSMFCore

commands:
  report:
    description: Reporting something.
    usage: /<command> <args>
  modularmsmf:
    description: Shows informations and more.
    usage: /<command> <args>
    aliases: [mmsmf]
  playershell:
    description: Enables console to act as a virtual player.
    usage: /<command> <playername>
  serverinfo:
    description: Shows running server software.
    usage: /<command>
  language:
    description: Choose your language.
    usage: /<command> <args>
  clearchat:
    description: Clears the chat completely
    usage: /<command>
    aliases: [cc, clr, clear, cls]
  list:
    description: Lists players
    usage: /<command>
    aliases: [listall]