name: ModularMSMF-Core
version: ${version}
description: The Core of the Modular Minecraft Server Management Framework
website: ${url}
authors: [Lightkeks, davidmc971]

api: none

main: io.github.davidmc971.modularmsmf.core.ModularMSMFCore

commands:
  report:
    description: Eine Meldung verfassen.
    usage: /<command> <args>
  mmsmf:
    description: Zeigt Infos und mehr an.
    usage: /<command> <args>
    aliases: [modularmsmf]
  playershell:
    description: Enables console to act as a virtual player.
    usage: /<command> <playername>
  serverinfo:
    description: Gibt die Serversoftware an.
    usage: /<command>
  language:
    description: Choose your language.
    usage: /<command> <args>
  clearchat:
    description: Clears the chat completely
    usage: /<command>
    aliases: [cc, clr, clear, cls]
